spring:
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天
    timeout: 2592000
    # 在多人登录同一账号时，是否共享会话 (为true时共用一个，为false时新登录挤掉旧登录)
    is-share: true
    # 是否尝试从请求体里读取token
    is-read-body: true
    # 是否尝试从header里读取token
    is-read-head: true
    # 是否尝试从cookie里读取token
    is-read-cookie: true
    # 是否在初始化配置时打印版本字符画
    is-v: true
  # 通用数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/lte?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Hikari 数据源专用配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  # jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
